export const premClubsArray = [
  "Arsenal",
  "Aston Villa",
  "Barnsley",
  "Birmingham City",
  "Blackburn Rovers",
  "Blackpool",
  "Bolton Wanderers",
  "Bournemouth",
  "Bradford City",
  "Brentford",
  "Brighton",
  "Burnley",
  "Cardiff City",
  "Charlton Athletic",
  "Chelsea",
  "Coventry City",
  "Crystal Palace",
  "Derby County",
  "Everton",
  "Fulham",
  "Huddersfield Town",
  "Hull City",
  "Ipswich Town",
  "Leeds United",
  "Leicster City",
  "Liverpool",
  "Luton Town",
  "Manchester City",
  "Manchester United",
  "Middlesbrough",
  "Newcastle United",
  "Norwich City",
  "Nottingham Forest",
  "Oldham Athletic",
  "Portsmouth",
  "Queen Park Rangers",
  "Reading",
  "Sheffield United",
  "Sheffield Wednesday",
  "Southampton",
  "Stoke City",
  "Sunderland",
  "Swansea City",
  "Swindon Town",
  "Tottenham Hotspur",
  "Watford",
  "West Bromwich Albion",
  "West Ham United",
  "Wigan Athletic",
  "Wolverhampton Wanderers",
];

export const laLigaClubsArray = [
  "Arenas",
  "Athletic Bilbao",
  "Atletico Madrid",
  "AD Almeria",
  "Albacete",
  "Atletico Tetuan",
  "Deportivo Alaves",
  "UD Almeria",
  "CD Alcoyano",
  "FC Barcelona",
  "Real Madrid CF",
  "Valencia CF",
  "RCD Espanyol",
  "Sevilla FC",
  "Real Sociedad",
  "RC Celta Vigo",
  "Real Betis",
  "Real Zaragoza",
  "Real Valladolid",
  "Deportivo La Coruna",
  "Racing de Santander",
  "CA Osasuna",
  "Sporting Gijon",
  "Real Oviedo",
  "UD Las Palmas",
  "RCD Mallorca",
  "Granada CF",
  "Villarreal CF",
  "Elche CF",
  "Rayo Vallecano",
  "Getafe CF",
  "CD Malaga",
  "Real Murcia CF",
  "Malaga CF",
  "Hercules CF",
  "Levante UD",
  "Cadiz CF",
  "CE Sabadell FC",
  "CD Tenerife",
  "UD Salamanca",
  "CD Castellon",
  "CD Logrones",
  "Cordoba CF",
  "SD Eibar",
  "Pontevedra CF",
  "Burgos CF",
  "Girona FC",
  "Recreativo de Huelva",
  "CD Leganes",
  "Real Union",
  "SD Compostela",
  "Gimnastic de Tarragona",
  "CD Numancia",
  "CE Europa",
  "Real Jaen",
  "Real Burgos CF",
  "UE Lleida",
  "CP Merida",
  "CF Extremadura",
  "SD Huesca",
  "Cultural Leonesa",
  "CD Condal",
  "Xerez CD",
];

export const removedArray = [
  "Its a team",
]