export const premClubsArray = [
  "Arsenal",
  "Aston Villa",
  "Barnsley",
  "Birmingham City",
  "Blackburn Rovers",
  "Blackpool",
  "Bolton Wanderers",
  "Bournemouth",
  "Bradford City",
  "Brentford",
  "Brighton",
  "Burnley",
  "Cardiff City",
  "Charlton Athletic",
  "Chelsea",
  "Coventry City",
  "Crystal Palace",
  "Derby County",
  "Everton",
  "Fulham",
  "Huddersfield Town",
  "Hull City",
  "Ipswich Town",
  "Leeds United",
  "Leicster City",
  "Liverpool",
  "Luton Town",
  "Manchester City",
  "Manchester United",
  "Middlesbrough",
  "Newcastle United",
  "Norwich City",
  "Nottingham Forest",
  "Oldham Athletic",
  "Portsmouth",
  "Queen Park Rangers",
  "Reading",
  "Sheffield United",
  "Sheffield Wednesday",
  "Southampton",
  "Stoke City",
  "Sunderland",
  "Swansea City",
  "Swindon Town",
  "Tottenham Hotspur",
  "Watford",
  "West Bromwich Albion",
  "West Ham United",
  "Wigan Athletic",
  "Wolverhampton Wanderers",
];

export const laLigaClubsArray = [
  "Arenas",
  "Athletic Bilbao",
  "Atletico Madrid",
  "AD Almeria",
  "Albacete",
  "Atletico Tetuan",
  "Deportivo Alaves",
  "UD Almeria",
  "CD Alcoyano",
  "FC Barcelona",
];

export const removedArray = [
  "Its a team",
]